export const nominationConfig = {
	guildId: "1456350064065904867",
	nominationChannelId: "1471742293055635536",
	reviewChannelId: "1519064274561929328",
	approverRoleIds: ["1477360613125787678"],
	targetRoleId: "1470356404706607227",
	requiredApprovals: 3,
	expirationHours: 48,
	maxReasonLength: 500,
	commandName: "nominate",
	copy: {
		title: "Shell Society nomination",
		wrongChannel: "Use this command in the Shell Society channel.",
		selfNomination: "You cannot nominate yourself.",
		reasonRequired: "Reason required. The shell demands context.",
		reasonTooLong: "Please keep the reason to 500 characters or fewer.",
		botNomination: "Bots cannot receive the shell. They know what they did.",
		userNotFound: "User not found in the server.",
		alreadyHasRole: "That user already has Shell Society.",
		alreadyPending: "That user already has an open Shell Society nomination.",
		noPermission: "Community Team only. Nice try though.",
		voteUnchanged: "That vote is already recorded.",
		voteRecorded: "Vote recorded.",
		voteSwitched: "Vote changed.",
		nominationPosted: "Nomination sent to the Community Team for review.",
		nominationPostFailed: "Could not post the nomination. Please try again.",
		nominationExpired: "This nomination has expired.",
		alreadyComplete: "This nomination is already complete.",
		roleAddFailed: "Could not add Shell Society. Check bot permissions and role order.",
		invalidNomination: "Could not load this nomination."
	}
}
